#!/bin/zsh

# # # # # # # # # # # # # # # # # # # #
# automatically populates a gitignore #
# based on a Github template          #
# # # # # # # # # # # # # # # # # # # #

newGit=()

#gets lines from template
#needs all this nonsense to not drop last line
while IFS="" read -r line || [ -n "$line" ]; do
    #exclude comments
    if [[ $line != '#'* ]];
    then newGit+=$line
    fi
done <test/template.txt

for line in $newGit; do
    echo $line
done
