#!/bin/zsh

# # # # # # # # # # # # # # # # # # # #
# automatically populates a gitignore #
# based on a Github template          #
# # # # # # # # # # # # # # # # # # # #

#clear output file first
: > test/output.txt

#gets lines from template
#needs all this nonsense to not drop last line
while IFS="" read -r line || [ -n "$line" ]; do

    #   exclude comments        files found
    if [[ $line != '#'* ]] && [[ $(find . -name $line) != '' ]];
    #append item to output
    then
        echo $(find . -name $line)
        echo $line >> test/output.txt
    fi

    #filepath
done <test/template.txt
