#!/bin/zsh

# # # # # # # # # # # # # # # # # # # # # # # # # #
# shortcuts the process of running Monkeys Typing #
# # # # # # # # # # # # # # # # # # # # # # # # # #

#if a filename isn't provided,
#default to Playground
fName="Playground"

#default field values
population=${2:-50}
initActions=${3:-100}
addRate=${4:-1}
addNum=${5:-$initActions}
numParents=${6:-2}
algToggle=${7:-true}

#if args
if [[ $# -gt 0 ]]; #TODO: shift right?
        #check if is int
then if [[ "$1" =~ ^-?[0-9]+$ ]];
     then 
        population=${1:-50}
        initActions=${2:-100}
        addRate=${3:-1}
        addNum=${4:-$initActions}
        numParents=${5:-2}
        algToggle=${6:-true}
     elif [[ "$1" = "false" || "$1" = "False" ]];
     then algToggle=$1
     else fName=$1
     fi
fi

./gradlew run -Pmain=cs2.AIP.$fName --args="$population $initActions $addRate $addNum $numParents $algToggle"
