#!/bin/zsh

# # # # # # # # # # # # # # # # # # # # # # # # # #
# shortcuts the process of running Monkeys Typing #
# # # # # # # # # # # # # # # # # # # # # # # # # #

#if a filename isn't provided,
#default to Playground
fName="Playground"

if [[ $# -gt 0 ]];
    then
        fName=$1
    fi

./gradlew run -Pmain=cs2.AIP.$fName
